openapi: 3.0.3
info:
  title: Описание методов API реализованных с помощью JWT аутентификации
  description: |-
    Тестовое задание: сделать простое API на Laravel с документацией в Swagger.

    Три метода:
      - Авторизация с использованием JWT
      - Получение данных об авторизованном пользователе по токену
      - Выход

    Код проекта загрузить на GitHub и прислать ссылку.

    [Код проекта на Github](https://github.com/sergopancha/laravel-jwt)
  contact:
    email: tulazis@yandex.ru
  version: 1.0.0
externalDocs:
  description: Описание и инструменты Swagger
  url: http://swagger.io
servers:
  - url: http://laravel-jwt.local/api
paths:
  /auth/register:
    post:
      tags:
        - auth
      summary: Create user
      description: new user
      operationId: createUser
      parameters:
        - name: name
          in: query
          description: The user name for login
          required: true
          schema:
            type: string
        - name: email
          in: query
          description: The user email for login
          required: true
          schema:
            type: string
        - name: password
          in: query
          description: The password for login
          required: true
          schema:
            type: string
        - name: password_confirmation
          in: query
          description: The password for login
          required: true
          schema:
            type: string
      requestBody:
        description: Created user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
          application/xml:
            schema:
              $ref: '#/components/schemas/UserRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserRegister'
            application/xml:
              schema:
                $ref: '#/components/schemas/UserRegister'
  /auth/login:
    post:
      tags:
        - auth
      summary: Logs user with  into the system and get token
      description: ''
      operationId: loginUser
      parameters:
        - name: username
          in: query
          description: The user name for login
          required: true
          schema:
            type: string
        - name: password
          in: query
          description: The password for login in clear text
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserLogin'
            application/xml:
              schema:
                $ref: '#/components/schemas/UserLogin'
        '401':
          description: Unauthorized
  /user/logout:
    post:
      tags:
        - auth
      summary: Logs out current logged in user session
      description: ''
      operationId: logoutUser
      parameters:
        - name: token
          in: header
          description: bearer token
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserLogout'
            application/xml:
              schema:
                $ref: '#/components/schemas/UserLogout'
  /auth/user-profile:
    get:
      tags:
        - auth
      summary: Get user profile with token
      description: ''
      operationId: getUserProfile
      parameters:
        - name: token
          in: header
          description: 'Send token for bearer authorization and get user profile data'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
            application/xml:
              schema:
                $ref: '#/components/schemas/UserProfile'
components:
  schemas:
    User:
      type: object
      properties:
        message:
          type: string
          format: int64
          example: 10
        username:
          type: string
          example: theUser
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: James
        email:
          type: string
          example: john@email.com
        password:
          type: string
          example: '12345'
        phone:
          type: string
          example: '12345'
        userStatus:
          type: integer
          description: User Status
          format: int32
          example: 1
      xml:
        name: user
    UserRequest:
      type: object
      properties:
        name:
          type: string
          example: FirstName LastName
        email:
          type: string
          example: john@email.com
        password:
          type: string
          example: '12345'
        password_confirmation:
          type: string
          example: '12345'
      xml:
        name: userRequest
    UserRegister:
      type: object
      properties:
        message:
          type: string
          example: User successfully registered
        user:
          type: object
          properties:
            name:
              type: string
              example: FirstName LastName
            email:
              type: string
              example: john@email.com
            updated_at:
              type: string
              example: 2024-03-10T11:48:05.000000Z
            created_at:
              type: string
              example: 2024-03-10T11:48:05.000000Z
            id:
              type: integer
              example: 2
      xml:
        name: userRegister
    UserProfile:
      type: object
      properties:
        name:
          type: string
          example: FirstName LastName
        email:
          type: string
          example: john@email.com
        email_verified_at:
          type: string
          example: 2024-03-10T11:48:05.000000Z
        updated_at:
          type: string
          example: 2024-03-10T11:48:05.000000Z
        created_at:
          type: string
          example: 2024-03-10T11:48:05.000000Z
        id:
          type: integer
          example: 2
      xml:
        name: userRegister
    UserLogin:
      type: object
      properties:
        access_token:
          type: string
          example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbGFyYXZlbC1qd3QubG9jYWwvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3MTAwODgxNTAsImV4cCI6MTcxMDA5MTc1MCwibmJmIjoxNzEwMDg4MTUwLCJqdGkiOiI4VmpQd2tqY3p5dDBLekU2Iiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.a5gVCcCTcFkAonM9ttuGi822ZzLowzysCGR2-GNT7pM
        token_type:
          type: string
          default: bearer
        expires_in:
          type: integer
          default: 3600
        user:
          type: object
          properties:
            name:
              type: string
              example: FirstName LastName
            email:
              type: string
              example: john@email.com
            email_verified_at:
              type: string
              example: 2024-03-10T11:48:05.000000Z
            updated_at:
              type: string
              example: 2024-03-10T11:48:05.000000Z
            created_at:
              type: string
              example: 2024-03-10T11:48:05.000000Z
            id:
              type: integer
              example: 2
      xml:
        name: userRegister
    UserLogout:
      type: object
      properties:
        message:
          type: string
          default: User successfully signed out
      xml:
        name: userLogout
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      xml:
        name: '##default'
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header
